-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_cyclic_block is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    stream_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_in_TVALID : IN STD_LOGIC;
    stream_in_TREADY : OUT STD_LOGIC;
    stream_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    stream_out_TVALID : OUT STD_LOGIC;
    stream_out_TREADY : IN STD_LOGIC;
    stream_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    stream_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    stream_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    stream_in2_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    stream_in2_TVALID : IN STD_LOGIC;
    stream_in2_TREADY : OUT STD_LOGIC;
    stream_in2_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in2_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    stream_in2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of matrix_cyclic_block is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrix_cyclic_block_matrix_cyclic_block,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.923000,HLS_SYN_LAT=43,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1515,HLS_SYN_LUT=1097,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";

    signal ap_rst_n_inv : STD_LOGIC;
    signal A_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal A_ce0 : STD_LOGIC;
    signal A_we0 : STD_LOGIC;
    signal A_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal A_1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal A_1_ce0 : STD_LOGIC;
    signal A_1_we0 : STD_LOGIC;
    signal A_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal A_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal A_2_ce0 : STD_LOGIC;
    signal A_2_we0 : STD_LOGIC;
    signal A_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal A_3_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal A_3_ce0 : STD_LOGIC;
    signal A_3_we0 : STD_LOGIC;
    signal A_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal B_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal B_ce0 : STD_LOGIC;
    signal B_we0 : STD_LOGIC;
    signal B_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal B_1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal B_1_ce0 : STD_LOGIC;
    signal B_1_we0 : STD_LOGIC;
    signal B_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal B_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal B_2_ce0 : STD_LOGIC;
    signal B_2_we0 : STD_LOGIC;
    signal B_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal B_3_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal B_3_ce0 : STD_LOGIC;
    signal B_3_we0 : STD_LOGIC;
    signal B_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_start : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_done : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_idle : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_ready : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_ce0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_we0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_1_ce0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_1_we0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_2_ce0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_2_we0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_3_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_3_ce0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_3_we0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_ce0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_we0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_1_ce0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_1_we0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_2_ce0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_2_we0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_3_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_3_ce0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_3_we0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_stream_in_TREADY : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_stream_in2_TREADY : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_start : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_done : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_idle : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_ready : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TREADY : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_ce0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_1_ce0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_2_ce0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_3_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_3_ce0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TVALID : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_ce0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_1_ce0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_2_ce0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_3_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_3_ce0 : STD_LOGIC;
    signal grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal stream_out_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal stream_out_TKEEP_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal stream_out_TSTRB_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal stream_out_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matrix_cyclic_block_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_in_TVALID : IN STD_LOGIC;
        stream_in2_TVALID : IN STD_LOGIC;
        B_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        B_ce0 : OUT STD_LOGIC;
        B_we0 : OUT STD_LOGIC;
        B_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        B_1_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        B_1_ce0 : OUT STD_LOGIC;
        B_1_we0 : OUT STD_LOGIC;
        B_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        B_2_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        B_2_ce0 : OUT STD_LOGIC;
        B_2_we0 : OUT STD_LOGIC;
        B_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        B_3_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        B_3_ce0 : OUT STD_LOGIC;
        B_3_we0 : OUT STD_LOGIC;
        B_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        A_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        A_ce0 : OUT STD_LOGIC;
        A_we0 : OUT STD_LOGIC;
        A_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        A_1_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        A_1_ce0 : OUT STD_LOGIC;
        A_1_we0 : OUT STD_LOGIC;
        A_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        A_2_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        A_2_ce0 : OUT STD_LOGIC;
        A_2_we0 : OUT STD_LOGIC;
        A_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        A_3_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        A_3_ce0 : OUT STD_LOGIC;
        A_3_we0 : OUT STD_LOGIC;
        A_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        stream_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        stream_in_TREADY : OUT STD_LOGIC;
        stream_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        stream_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        stream_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        stream_in2_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        stream_in2_TREADY : OUT STD_LOGIC;
        stream_in2_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        stream_in2_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        stream_in2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component matrix_cyclic_block_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_out_TREADY : IN STD_LOGIC;
        B_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        B_ce0 : OUT STD_LOGIC;
        B_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        B_1_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        B_1_ce0 : OUT STD_LOGIC;
        B_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        B_2_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        B_2_ce0 : OUT STD_LOGIC;
        B_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        B_3_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        B_3_ce0 : OUT STD_LOGIC;
        B_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        stream_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        stream_out_TVALID : OUT STD_LOGIC;
        stream_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        stream_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        stream_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        A_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        A_ce0 : OUT STD_LOGIC;
        A_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        A_1_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        A_1_ce0 : OUT STD_LOGIC;
        A_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        A_2_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        A_2_ce0 : OUT STD_LOGIC;
        A_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        A_3_address0 : OUT STD_LOGIC_VECTOR (1 downto 0);
        A_3_ce0 : OUT STD_LOGIC;
        A_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matrix_cyclic_block_A_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    A_U : component matrix_cyclic_block_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 4,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => A_address0,
        ce0 => A_ce0,
        we0 => A_we0,
        d0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_d0,
        q0 => A_q0);

    A_1_U : component matrix_cyclic_block_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 4,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => A_1_address0,
        ce0 => A_1_ce0,
        we0 => A_1_we0,
        d0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_1_d0,
        q0 => A_1_q0);

    A_2_U : component matrix_cyclic_block_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 4,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => A_2_address0,
        ce0 => A_2_ce0,
        we0 => A_2_we0,
        d0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_2_d0,
        q0 => A_2_q0);

    A_3_U : component matrix_cyclic_block_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 4,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => A_3_address0,
        ce0 => A_3_ce0,
        we0 => A_3_we0,
        d0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_3_d0,
        q0 => A_3_q0);

    B_U : component matrix_cyclic_block_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 4,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => B_address0,
        ce0 => B_ce0,
        we0 => B_we0,
        d0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_d0,
        q0 => B_q0);

    B_1_U : component matrix_cyclic_block_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 4,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => B_1_address0,
        ce0 => B_1_ce0,
        we0 => B_1_we0,
        d0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_1_d0,
        q0 => B_1_q0);

    B_2_U : component matrix_cyclic_block_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 4,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => B_2_address0,
        ce0 => B_2_ce0,
        we0 => B_2_we0,
        d0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_2_d0,
        q0 => B_2_q0);

    B_3_U : component matrix_cyclic_block_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 4,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => B_3_address0,
        ce0 => B_3_ce0,
        we0 => B_3_we0,
        d0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_3_d0,
        q0 => B_3_q0);

    grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90 : component matrix_cyclic_block_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_start,
        ap_done => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_done,
        ap_idle => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_idle,
        ap_ready => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_ready,
        stream_in_TVALID => stream_in_TVALID,
        stream_in2_TVALID => stream_in2_TVALID,
        B_address0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_address0,
        B_ce0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_ce0,
        B_we0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_we0,
        B_d0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_d0,
        B_1_address0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_1_address0,
        B_1_ce0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_1_ce0,
        B_1_we0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_1_we0,
        B_1_d0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_1_d0,
        B_2_address0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_2_address0,
        B_2_ce0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_2_ce0,
        B_2_we0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_2_we0,
        B_2_d0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_2_d0,
        B_3_address0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_3_address0,
        B_3_ce0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_3_ce0,
        B_3_we0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_3_we0,
        B_3_d0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_3_d0,
        A_address0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_address0,
        A_ce0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_ce0,
        A_we0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_we0,
        A_d0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_d0,
        A_1_address0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_1_address0,
        A_1_ce0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_1_ce0,
        A_1_we0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_1_we0,
        A_1_d0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_1_d0,
        A_2_address0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_2_address0,
        A_2_ce0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_2_ce0,
        A_2_we0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_2_we0,
        A_2_d0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_2_d0,
        A_3_address0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_3_address0,
        A_3_ce0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_3_ce0,
        A_3_we0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_3_we0,
        A_3_d0 => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_3_d0,
        stream_in_TDATA => stream_in_TDATA,
        stream_in_TREADY => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_stream_in_TREADY,
        stream_in_TKEEP => stream_in_TKEEP,
        stream_in_TSTRB => stream_in_TSTRB,
        stream_in_TLAST => stream_in_TLAST,
        stream_in2_TDATA => stream_in2_TDATA,
        stream_in2_TREADY => grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_stream_in2_TREADY,
        stream_in2_TKEEP => stream_in2_TKEEP,
        stream_in2_TSTRB => stream_in2_TSTRB,
        stream_in2_TLAST => stream_in2_TLAST);

    grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126 : component matrix_cyclic_block_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_start,
        ap_done => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_done,
        ap_idle => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_idle,
        ap_ready => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_ready,
        stream_out_TREADY => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TREADY,
        B_address0 => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_address0,
        B_ce0 => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_ce0,
        B_q0 => B_q0,
        B_1_address0 => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_1_address0,
        B_1_ce0 => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_1_ce0,
        B_1_q0 => B_1_q0,
        B_2_address0 => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_2_address0,
        B_2_ce0 => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_2_ce0,
        B_2_q0 => B_2_q0,
        B_3_address0 => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_3_address0,
        B_3_ce0 => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_3_ce0,
        B_3_q0 => B_3_q0,
        stream_out_TDATA => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TDATA,
        stream_out_TVALID => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TVALID,
        stream_out_TKEEP => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TKEEP,
        stream_out_TSTRB => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TSTRB,
        stream_out_TLAST => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TLAST,
        A_address0 => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_address0,
        A_ce0 => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_ce0,
        A_q0 => A_q0,
        A_1_address0 => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_1_address0,
        A_1_ce0 => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_1_ce0,
        A_1_q0 => A_1_q0,
        A_2_address0 => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_2_address0,
        A_2_ce0 => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_2_ce0,
        A_2_q0 => A_2_q0,
        A_3_address0 => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_3_address0,
        A_3_ce0 => grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_3_ce0,
        A_3_q0 => A_3_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_ready = ap_const_logic_1)) then 
                    grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_ready = ap_const_logic_1)) then 
                    grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TVALID = ap_const_logic_1))) then
                stream_out_TDATA_reg <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TDATA;
                stream_out_TKEEP_reg <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TKEEP;
                stream_out_TLAST_reg <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TLAST;
                stream_out_TSTRB_reg <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TSTRB;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_done, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_done, ap_CS_fsm, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;

    A_1_address0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_1_address0, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_1_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            A_1_address0 <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            A_1_address0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_1_address0;
        else 
            A_1_address0 <= "XX";
        end if; 
    end process;


    A_1_ce0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_1_ce0, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_1_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            A_1_ce0 <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            A_1_ce0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_1_ce0;
        else 
            A_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    A_1_we0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_1_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            A_1_we0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_1_we0;
        else 
            A_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    A_2_address0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_2_address0, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_2_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            A_2_address0 <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            A_2_address0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_2_address0;
        else 
            A_2_address0 <= "XX";
        end if; 
    end process;


    A_2_ce0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_2_ce0, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_2_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            A_2_ce0 <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            A_2_ce0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_2_ce0;
        else 
            A_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    A_2_we0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_2_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            A_2_we0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_2_we0;
        else 
            A_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    A_3_address0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_3_address0, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_3_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            A_3_address0 <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            A_3_address0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_3_address0;
        else 
            A_3_address0 <= "XX";
        end if; 
    end process;


    A_3_ce0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_3_ce0, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_3_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            A_3_ce0 <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            A_3_ce0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_3_ce0;
        else 
            A_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    A_3_we0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_3_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            A_3_we0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_3_we0;
        else 
            A_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    A_address0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_address0, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            A_address0 <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            A_address0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_address0;
        else 
            A_address0 <= "XX";
        end if; 
    end process;


    A_ce0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_ce0, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            A_ce0 <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_A_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            A_ce0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_ce0;
        else 
            A_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    A_we0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            A_we0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_A_we0;
        else 
            A_we0 <= ap_const_logic_0;
        end if; 
    end process;


    B_1_address0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_1_address0, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_1_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            B_1_address0 <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            B_1_address0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_1_address0;
        else 
            B_1_address0 <= "XX";
        end if; 
    end process;


    B_1_ce0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_1_ce0, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_1_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            B_1_ce0 <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            B_1_ce0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_1_ce0;
        else 
            B_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    B_1_we0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_1_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            B_1_we0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_1_we0;
        else 
            B_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    B_2_address0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_2_address0, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_2_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            B_2_address0 <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            B_2_address0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_2_address0;
        else 
            B_2_address0 <= "XX";
        end if; 
    end process;


    B_2_ce0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_2_ce0, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_2_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            B_2_ce0 <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            B_2_ce0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_2_ce0;
        else 
            B_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    B_2_we0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_2_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            B_2_we0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_2_we0;
        else 
            B_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    B_3_address0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_3_address0, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_3_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            B_3_address0 <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            B_3_address0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_3_address0;
        else 
            B_3_address0 <= "XX";
        end if; 
    end process;


    B_3_ce0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_3_ce0, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_3_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            B_3_ce0 <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            B_3_ce0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_3_ce0;
        else 
            B_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    B_3_we0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_3_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            B_3_we0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_3_we0;
        else 
            B_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    B_address0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_address0, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            B_address0 <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            B_address0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_address0;
        else 
            B_address0 <= "XX";
        end if; 
    end process;


    B_ce0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_ce0, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            B_ce0 <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_B_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            B_ce0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_ce0;
        else 
            B_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    B_we0_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            B_we0 <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_B_we0;
        else 
            B_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;

    ap_ST_fsm_state2_blk_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_done)
    begin
        if ((grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_done)
    begin
        if ((grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_start <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_ap_start_reg;
    grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TREADY <= (stream_out_TREADY and ap_CS_fsm_state4);
    grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_start <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_ap_start_reg;

    stream_in2_TREADY_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_stream_in2_TREADY, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            stream_in2_TREADY <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_stream_in2_TREADY;
        else 
            stream_in2_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    stream_in_TREADY_assign_proc : process(grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_stream_in_TREADY, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            stream_in_TREADY <= grp_matrix_cyclic_block_Pipeline_read_A_and_B_VITIS_LOOP_28_1_fu_90_stream_in_TREADY;
        else 
            stream_in_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    stream_out_TDATA_assign_proc : process(grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TDATA, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TVALID, ap_CS_fsm_state4, stream_out_TDATA_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TVALID = ap_const_logic_1))) then 
            stream_out_TDATA <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TDATA;
        else 
            stream_out_TDATA <= stream_out_TDATA_reg;
        end if; 
    end process;


    stream_out_TKEEP_assign_proc : process(grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TVALID, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TKEEP, ap_CS_fsm_state4, stream_out_TKEEP_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TVALID = ap_const_logic_1))) then 
            stream_out_TKEEP <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TKEEP;
        else 
            stream_out_TKEEP <= stream_out_TKEEP_reg;
        end if; 
    end process;


    stream_out_TLAST_assign_proc : process(grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TVALID, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TLAST, ap_CS_fsm_state4, stream_out_TLAST_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TVALID = ap_const_logic_1))) then 
            stream_out_TLAST <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TLAST;
        else 
            stream_out_TLAST <= stream_out_TLAST_reg;
        end if; 
    end process;


    stream_out_TSTRB_assign_proc : process(grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TVALID, grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TSTRB, ap_CS_fsm_state4, stream_out_TSTRB_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TVALID = ap_const_logic_1))) then 
            stream_out_TSTRB <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TSTRB;
        else 
            stream_out_TSTRB <= stream_out_TSTRB_reg;
        end if; 
    end process;

    stream_out_TVALID <= grp_matrix_cyclic_block_Pipeline_Matrix_Loop_VITIS_LOOP_39_2_fu_126_stream_out_TVALID;
end behav;
