#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("Q_tile_in_TDATA", 32, hls_in, 0, "axis", "in_data", 1),
	Port_Property("Q_tile_in_TVALID", 1, hls_in, 3, "axis", "in_vld", 1),
	Port_Property("Q_tile_in_TREADY", 1, hls_out, 3, "axis", "in_acc", 1),
	Port_Property("Q_tile_in_TKEEP", 4, hls_in, 1, "axis", "in_data", 1),
	Port_Property("Q_tile_in_TSTRB", 4, hls_in, 2, "axis", "in_data", 1),
	Port_Property("Q_tile_in_TLAST", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("K_tile_in_TDATA", 32, hls_in, 4, "axis", "in_data", 1),
	Port_Property("K_tile_in_TVALID", 1, hls_in, 7, "axis", "in_vld", 1),
	Port_Property("K_tile_in_TREADY", 1, hls_out, 7, "axis", "in_acc", 1),
	Port_Property("K_tile_in_TKEEP", 4, hls_in, 5, "axis", "in_data", 1),
	Port_Property("K_tile_in_TSTRB", 4, hls_in, 6, "axis", "in_data", 1),
	Port_Property("K_tile_in_TLAST", 1, hls_in, 7, "axis", "in_data", 1),
	Port_Property("V_tile_in_TDATA", 32, hls_in, 8, "axis", "in_data", 1),
	Port_Property("V_tile_in_TVALID", 1, hls_in, 11, "axis", "in_vld", 1),
	Port_Property("V_tile_in_TREADY", 1, hls_out, 11, "axis", "in_acc", 1),
	Port_Property("V_tile_in_TKEEP", 4, hls_in, 9, "axis", "in_data", 1),
	Port_Property("V_tile_in_TSTRB", 4, hls_in, 10, "axis", "in_data", 1),
	Port_Property("V_tile_in_TLAST", 1, hls_in, 11, "axis", "in_data", 1),
	Port_Property("O_tile_out_TDATA", 32, hls_out, 12, "axis", "out_data", 1),
	Port_Property("O_tile_out_TVALID", 1, hls_out, 15, "axis", "out_vld", 1),
	Port_Property("O_tile_out_TREADY", 1, hls_in, 15, "axis", "out_acc", 1),
	Port_Property("O_tile_out_TKEEP", 4, hls_out, 13, "axis", "out_data", 1),
	Port_Property("O_tile_out_TSTRB", 4, hls_out, 14, "axis", "out_data", 1),
	Port_Property("O_tile_out_TLAST", 1, hls_out, 15, "axis", "out_data", 1),
};
const char* HLS_Design_Meta::dut_name = "flashattn";
