transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vlib activehdl/xilinx_vip
vlib activehdl/xpm
vlib activehdl/xbip_utils_v3_0_14
vlib activehdl/axi_utils_v2_0_10
vlib activehdl/xbip_pipe_v3_0_10
vlib activehdl/xbip_dsp48_wrapper_v3_0_6
vlib activehdl/mult_gen_v12_0_22
vlib activehdl/floating_point_v7_1_19
vlib activehdl/xil_defaultlib
vlib activehdl/axi_infrastructure_v1_1_0
vlib activehdl/axi_vip_v1_1_19
vlib activehdl/processing_system7_vip_v1_0_21
vlib activehdl/lib_pkg_v1_0_4
vlib activehdl/fifo_generator_v13_2_11
vlib activehdl/lib_fifo_v1_0_20
vlib activehdl/lib_srl_fifo_v1_0_4
vlib activehdl/lib_cdc_v1_0_3
vlib activehdl/axi_datamover_v5_1_35
vlib activehdl/axi_sg_v4_1_19
vlib activehdl/axi_dma_v7_1_34
vlib activehdl/xlconstant_v1_1_9
vlib activehdl/proc_sys_reset_v5_0_16
vlib activehdl/smartconnect_v1_0
vlib activehdl/axi_register_slice_v2_1_33
vlib activehdl/generic_baseblocks_v2_1_2
vlib activehdl/axi_data_fifo_v2_1_32
vlib activehdl/axi_crossbar_v2_1_34
vlib activehdl/axi_protocol_converter_v2_1_33
vlib activehdl/axi_clock_converter_v2_1_32
vlib activehdl/blk_mem_gen_v8_4_9
vlib activehdl/axi_dwidth_converter_v2_1_33

vmap xilinx_vip activehdl/xilinx_vip
vmap xpm activehdl/xpm
vmap xbip_utils_v3_0_14 activehdl/xbip_utils_v3_0_14
vmap axi_utils_v2_0_10 activehdl/axi_utils_v2_0_10
vmap xbip_pipe_v3_0_10 activehdl/xbip_pipe_v3_0_10
vmap xbip_dsp48_wrapper_v3_0_6 activehdl/xbip_dsp48_wrapper_v3_0_6
vmap mult_gen_v12_0_22 activehdl/mult_gen_v12_0_22
vmap floating_point_v7_1_19 activehdl/floating_point_v7_1_19
vmap xil_defaultlib activehdl/xil_defaultlib
vmap axi_infrastructure_v1_1_0 activehdl/axi_infrastructure_v1_1_0
vmap axi_vip_v1_1_19 activehdl/axi_vip_v1_1_19
vmap processing_system7_vip_v1_0_21 activehdl/processing_system7_vip_v1_0_21
vmap lib_pkg_v1_0_4 activehdl/lib_pkg_v1_0_4
vmap fifo_generator_v13_2_11 activehdl/fifo_generator_v13_2_11
vmap lib_fifo_v1_0_20 activehdl/lib_fifo_v1_0_20
vmap lib_srl_fifo_v1_0_4 activehdl/lib_srl_fifo_v1_0_4
vmap lib_cdc_v1_0_3 activehdl/lib_cdc_v1_0_3
vmap axi_datamover_v5_1_35 activehdl/axi_datamover_v5_1_35
vmap axi_sg_v4_1_19 activehdl/axi_sg_v4_1_19
vmap axi_dma_v7_1_34 activehdl/axi_dma_v7_1_34
vmap xlconstant_v1_1_9 activehdl/xlconstant_v1_1_9
vmap proc_sys_reset_v5_0_16 activehdl/proc_sys_reset_v5_0_16
vmap smartconnect_v1_0 activehdl/smartconnect_v1_0
vmap axi_register_slice_v2_1_33 activehdl/axi_register_slice_v2_1_33
vmap generic_baseblocks_v2_1_2 activehdl/generic_baseblocks_v2_1_2
vmap axi_data_fifo_v2_1_32 activehdl/axi_data_fifo_v2_1_32
vmap axi_crossbar_v2_1_34 activehdl/axi_crossbar_v2_1_34
vmap axi_protocol_converter_v2_1_33 activehdl/axi_protocol_converter_v2_1_33
vmap axi_clock_converter_v2_1_32 activehdl/axi_clock_converter_v2_1_32
vmap blk_mem_gen_v8_4_9 activehdl/blk_mem_gen_v8_4_9
vmap axi_dwidth_converter_v2_1_33 activehdl/axi_dwidth_converter_v2_1_33

vlog -work xilinx_vip  -sv2k12 "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"C:/Xilinx/Vivado/2024.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93  \
"C:/Xilinx/Vivado/2024.2/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -work xbip_utils_v3_0_14 -93  \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/b27f/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

vcom -work axi_utils_v2_0_10 -93  \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/7e77/hdl/axi_utils_v2_0_vh_rfs.vhd" \

vcom -work xbip_pipe_v3_0_10 -93  \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/d531/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \

vcom -work xbip_dsp48_wrapper_v3_0_6 -93  \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f596/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \

vcom -work mult_gen_v12_0_22 -93  \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/e765/hdl/mult_gen_v12_0_vh_rfs.vhd" \

vcom -work floating_point_v7_1_19 -93  \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/bf3d/hdl/floating_point_v7_1_rfs.vhd" \

vlog -work floating_point_v7_1_19  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/bf3d/hdl/floating_point_v7_1_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/ip/flashattn_fadd_32ns_32ns_32_5_full_dsp_1_ip.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/ip/flashattn_faddfsub_32ns_32ns_32_5_full_dsp_1_ip.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/ip/flashattn_fcmp_32ns_32ns_1_2_no_dsp_1_ip.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/ip/flashattn_fdiv_32ns_32ns_32_16_no_dsp_1_ip.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/ip/flashattn_fexp_32ns_32ns_32_10_full_dsp_1_ip.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/ip/flashattn_fmul_32ns_32ns_32_4_max_dsp_1_ip.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_exp_sum_RAM_AUTO_1R1W.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_fadd_32ns_32ns_32_5_full_dsp_1.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_faddfsub_32ns_32ns_32_5_full_dsp_1.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_fcmp_32ns_32ns_1_2_no_dsp_1.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_fdiv_32ns_32ns_32_16_no_dsp_1.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_fexp_32ns_32ns_32_10_full_dsp_1.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_flashattn_Pipeline_Compute_Online_Softmax_VITIS_LOOP_72_4.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_flashattn_Pipeline_Init_Accumulators.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_flashattn_Pipeline_Normalize_And_Stream_Output_VITIS_LOOP_120_8.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_45_2.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_flashattn_Pipeline_Read_Q_VITIS_LOOP_34_1.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_flow_control_loop_pipe_sequential_init.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_fmul_32ns_32ns_32_4_max_dsp_1.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_hls_deadlock_idx0_monitor.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_hls_deadlock_idx2_monitor.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_Q_tile_RAM_AUTO_1R1W.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn_sparsemux_129_6_32_1_1.v" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog/flashattn.v" \
"../../../bd/flashattn_bd/ip/flashattn_bd_flashattn_0_0/sim/flashattn_bd_flashattn_0_0.v" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_19  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/8c45/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_21  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../bd/flashattn_bd/ip/flashattn_bd_processing_system7_0_0/sim/flashattn_bd_processing_system7_0_0.v" \

vcom -work lib_pkg_v1_0_4 -93  \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/8c68/hdl/lib_pkg_v1_0_rfs.vhd" \

vlog -work fifo_generator_v13_2_11  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/6080/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_11 -93  \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/6080/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_11  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/6080/hdl/fifo_generator_v13_2_rfs.v" \

vcom -work lib_fifo_v1_0_20 -93  \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/e160/hdl/lib_fifo_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_4 -93  \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/1e5a/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work lib_cdc_v1_0_3 -93  \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_35 -93  \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/4277/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vcom -work axi_sg_v4_1_19 -93  \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/fc5d/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_dma_v7_1_34 -93  \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/70ff/hdl/axi_dma_v7_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_dma_0_0/sim/flashattn_bd_axi_dma_0_0.vhd" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_dma_1_0/sim/flashattn_bd_axi_dma_1_0.vhd" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_dma_2_0/sim/flashattn_bd_axi_dma_2_0.vhd" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_dma_3_0/sim/flashattn_bd_axi_dma_3_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/sim/bd_b8a5.v" \

vlog -work xlconstant_v1_1_9  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_0/sim/bd_b8a5_one_0.v" \

vcom -work proc_sys_reset_v5_0_16 -93  \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0831/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_1/sim/bd_b8a5_psr_aclk_0.vhd" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_2/sim/bd_b8a5_arinsw_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_3/sim/bd_b8a5_rinsw_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_4/sim/bd_b8a5_awinsw_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_5/sim/bd_b8a5_winsw_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_6/sim/bd_b8a5_binsw_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_7/sim/bd_b8a5_aroutsw_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_8/sim/bd_b8a5_routsw_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_9/sim/bd_b8a5_awoutsw_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_10/sim/bd_b8a5_woutsw_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_11/sim/bd_b8a5_boutsw_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_12/sim/bd_b8a5_arni_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_13/sim/bd_b8a5_rni_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_14/sim/bd_b8a5_awni_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_15/sim/bd_b8a5_wni_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_16/sim/bd_b8a5_bni_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f49a/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_17/sim/bd_b8a5_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_18/sim/bd_b8a5_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/63ed/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_19/sim/bd_b8a5_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_20/sim/bd_b8a5_s00a2s_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_21/sim/bd_b8a5_sarn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_22/sim/bd_b8a5_srn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_23/sim/bd_b8a5_sawn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_24/sim/bd_b8a5_swn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_25/sim/bd_b8a5_sbn_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_26/sim/bd_b8a5_m00s2a_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_27/sim/bd_b8a5_m00arn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_28/sim/bd_b8a5_m00rn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_29/sim/bd_b8a5_m00awn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_30/sim/bd_b8a5_m00wn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_31/sim/bd_b8a5_m00bn_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/37bc/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_32/sim/bd_b8a5_m00e_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_33/sim/bd_b8a5_m01s2a_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_34/sim/bd_b8a5_m01arn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_35/sim/bd_b8a5_m01rn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_36/sim/bd_b8a5_m01awn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_37/sim/bd_b8a5_m01wn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_38/sim/bd_b8a5_m01bn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_39/sim/bd_b8a5_m01e_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_40/sim/bd_b8a5_m02s2a_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_41/sim/bd_b8a5_m02arn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_42/sim/bd_b8a5_m02rn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_43/sim/bd_b8a5_m02awn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_44/sim/bd_b8a5_m02wn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_45/sim/bd_b8a5_m02bn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_46/sim/bd_b8a5_m02e_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_47/sim/bd_b8a5_m03s2a_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_48/sim/bd_b8a5_m03arn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_49/sim/bd_b8a5_m03rn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_50/sim/bd_b8a5_m03awn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_51/sim/bd_b8a5_m03wn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_52/sim/bd_b8a5_m03bn_0.sv" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/bd_0/ip/ip_53/sim/bd_b8a5_m03e_0.sv" \

vlog -work axi_register_slice_v2_1_33  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/3ee4/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/sim/flashattn_bd_axi_smc_0.v" \

vcom -work xil_defaultlib -93  \
"../../../bd/flashattn_bd/ip/flashattn_bd_rst_ps7_0_100M_0/sim/flashattn_bd_rst_ps7_0_100M_0.vhd" \

vlog -work generic_baseblocks_v2_1_2  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0c28/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_32  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/65ce/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_34  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/a7e3/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_xbar_0/sim/flashattn_bd_axi_interconnect_0_imp_xbar_0.v" \

vlog -work axi_protocol_converter_v2_1_33  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/27ae/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work axi_clock_converter_v2_1_32  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/a4e8/hdl/axi_clock_converter_v2_1_vl_rfs.v" \

vlog -work blk_mem_gen_v8_4_9  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/5ec1/simulation/blk_mem_gen_v8_4.v" \

vlog -work axi_dwidth_converter_v2_1_33  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/d794/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/2616/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/ec67/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/86fe/hdl" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/f0b6/hdl/verilog" "+incdir+../../../../flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ipshared/0127/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2024.2/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xbip_utils_v3_0_14 -l axi_utils_v2_0_10 -l xbip_pipe_v3_0_10 -l xbip_dsp48_wrapper_v3_0_6 -l mult_gen_v12_0_22 -l floating_point_v7_1_19 -l xil_defaultlib -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_19 -l processing_system7_vip_v1_0_21 -l lib_pkg_v1_0_4 -l fifo_generator_v13_2_11 -l lib_fifo_v1_0_20 -l lib_srl_fifo_v1_0_4 -l lib_cdc_v1_0_3 -l axi_datamover_v5_1_35 -l axi_sg_v4_1_19 -l axi_dma_v7_1_34 -l xlconstant_v1_1_9 -l proc_sys_reset_v5_0_16 -l smartconnect_v1_0 -l axi_register_slice_v2_1_33 -l generic_baseblocks_v2_1_2 -l axi_data_fifo_v2_1_32 -l axi_crossbar_v2_1_34 -l axi_protocol_converter_v2_1_33 -l axi_clock_converter_v2_1_32 -l blk_mem_gen_v8_4_9 -l axi_dwidth_converter_v2_1_33 \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_auto_us_0/sim/flashattn_bd_axi_interconnect_0_imp_auto_us_0.v" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_auto_us_1/sim/flashattn_bd_axi_interconnect_0_imp_auto_us_1.v" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_auto_us_2/sim/flashattn_bd_axi_interconnect_0_imp_auto_us_2.v" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_auto_us_3/sim/flashattn_bd_axi_interconnect_0_imp_auto_us_3.v" \
"../../../bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_auto_pc_0/sim/flashattn_bd_axi_interconnect_0_imp_auto_pc_0.v" \
"../../../bd/flashattn_bd/sim/flashattn_bd.v" \

vlog -work xil_defaultlib \
"glbl.v"

