// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="flashattn_flashattn,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=8212,HLS_SYN_TPT=none,HLS_SYN_MEM=24,HLS_SYN_DSP=0,HLS_SYN_FF=881,HLS_SYN_LUT=1589,HLS_VERSION=2024_2}" *)

module flashattn (
        ap_clk,
        ap_rst_n,
        Q_tile_in_TDATA,
        Q_tile_in_TVALID,
        Q_tile_in_TREADY,
        Q_tile_in_TKEEP,
        Q_tile_in_TSTRB,
        Q_tile_in_TLAST,
        K_tile_in_TDATA,
        K_tile_in_TVALID,
        K_tile_in_TREADY,
        K_tile_in_TKEEP,
        K_tile_in_TSTRB,
        K_tile_in_TLAST,
        V_tile_in_TDATA,
        V_tile_in_TVALID,
        V_tile_in_TREADY,
        V_tile_in_TKEEP,
        V_tile_in_TSTRB,
        V_tile_in_TLAST,
        O_tile_out_TDATA,
        O_tile_out_TVALID,
        O_tile_out_TREADY,
        O_tile_out_TKEEP,
        O_tile_out_TSTRB,
        O_tile_out_TLAST
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst_n;
input  [31:0] Q_tile_in_TDATA;
input   Q_tile_in_TVALID;
output   Q_tile_in_TREADY;
input  [3:0] Q_tile_in_TKEEP;
input  [3:0] Q_tile_in_TSTRB;
input  [0:0] Q_tile_in_TLAST;
input  [31:0] K_tile_in_TDATA;
input   K_tile_in_TVALID;
output   K_tile_in_TREADY;
input  [3:0] K_tile_in_TKEEP;
input  [3:0] K_tile_in_TSTRB;
input  [0:0] K_tile_in_TLAST;
input  [31:0] V_tile_in_TDATA;
input   V_tile_in_TVALID;
output   V_tile_in_TREADY;
input  [3:0] V_tile_in_TKEEP;
input  [3:0] V_tile_in_TSTRB;
input  [0:0] V_tile_in_TLAST;
output  [31:0] O_tile_out_TDATA;
output   O_tile_out_TVALID;
input   O_tile_out_TREADY;
output  [3:0] O_tile_out_TKEEP;
output  [3:0] O_tile_out_TSTRB;
output  [0:0] O_tile_out_TLAST;

reg Q_tile_in_TREADY;
reg K_tile_in_TREADY;
reg V_tile_in_TREADY;
reg[31:0] O_tile_out_TDATA;
reg[3:0] O_tile_out_TKEEP;
reg[3:0] O_tile_out_TSTRB;
reg[0:0] O_tile_out_TLAST;

 reg    ap_rst_n_inv;
reg   [11:0] Q_tile_address0;
reg    Q_tile_ce0;
reg    Q_tile_we0;
wire   [31:0] Q_tile_q0;
reg   [11:0] K_tile_address0;
reg    K_tile_ce0;
reg    K_tile_we0;
wire   [31:0] K_tile_q0;
reg   [11:0] V_tile_address0;
reg    V_tile_ce0;
reg    V_tile_we0;
wire   [31:0] V_tile_q0;
wire    grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start;
wire    grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_done;
wire    grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_idle;
wire    grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_ready;
wire   [11:0] grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_address0;
wire    grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_ce0;
wire    grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_we0;
wire   [31:0] grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_d0;
wire    grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_in_TREADY;
wire    grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start;
wire    grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_done;
wire    grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_idle;
wire    grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_ready;
wire   [11:0] grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_address0;
wire    grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_ce0;
wire    grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_we0;
wire   [31:0] grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_d0;
wire   [11:0] grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_address0;
wire    grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_ce0;
wire    grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_we0;
wire   [31:0] grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_d0;
wire    grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_in_TREADY;
wire    grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_in_TREADY;
wire    grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start;
wire    grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_done;
wire    grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_idle;
wire    grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_ready;
wire    grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TREADY;
wire   [11:0] grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_Q_tile_address0;
wire    grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_Q_tile_ce0;
wire   [11:0] grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_K_tile_address0;
wire    grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_K_tile_ce0;
wire   [11:0] grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_V_tile_address0;
wire    grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_V_tile_ce0;
wire   [31:0] grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TDATA;
wire    grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID;
wire   [3:0] grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TKEEP;
wire   [3:0] grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TSTRB;
wire   [0:0] grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TLAST;
reg    grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
reg    grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start_reg;
reg    grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg   [31:0] O_tile_out_TDATA_reg;
reg   [3:0] O_tile_out_TKEEP_reg;
reg   [3:0] O_tile_out_TSTRB_reg;
reg   [0:0] O_tile_out_TLAST_reg;
reg   [3:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start_reg = 1'b0;
#0 grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start_reg = 1'b0;
end

flashattn_Q_tile_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
Q_tile_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(Q_tile_address0),
    .ce0(Q_tile_ce0),
    .we0(Q_tile_we0),
    .d0(grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_d0),
    .q0(Q_tile_q0)
);

flashattn_Q_tile_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
K_tile_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(K_tile_address0),
    .ce0(K_tile_ce0),
    .we0(K_tile_we0),
    .d0(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_d0),
    .q0(K_tile_q0)
);

flashattn_Q_tile_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
V_tile_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(V_tile_address0),
    .ce0(V_tile_ce0),
    .we0(V_tile_we0),
    .d0(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_d0),
    .q0(V_tile_q0)
);

flashattn_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1 grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start),
    .ap_done(grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_done),
    .ap_idle(grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_idle),
    .ap_ready(grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_ready),
    .Q_tile_in_TVALID(Q_tile_in_TVALID),
    .Q_tile_address0(grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_address0),
    .Q_tile_ce0(grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_ce0),
    .Q_tile_we0(grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_we0),
    .Q_tile_d0(grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_d0),
    .Q_tile_in_TDATA(Q_tile_in_TDATA),
    .Q_tile_in_TREADY(grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_in_TREADY),
    .Q_tile_in_TKEEP(Q_tile_in_TKEEP),
    .Q_tile_in_TSTRB(Q_tile_in_TSTRB),
    .Q_tile_in_TLAST(Q_tile_in_TLAST)
);

flashattn_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2 grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start),
    .ap_done(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_done),
    .ap_idle(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_idle),
    .ap_ready(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_ready),
    .K_tile_in_TVALID(K_tile_in_TVALID),
    .V_tile_in_TVALID(V_tile_in_TVALID),
    .K_tile_address0(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_address0),
    .K_tile_ce0(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_ce0),
    .K_tile_we0(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_we0),
    .K_tile_d0(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_d0),
    .V_tile_address0(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_address0),
    .V_tile_ce0(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_ce0),
    .V_tile_we0(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_we0),
    .V_tile_d0(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_d0),
    .K_tile_in_TDATA(K_tile_in_TDATA),
    .K_tile_in_TREADY(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_in_TREADY),
    .K_tile_in_TKEEP(K_tile_in_TKEEP),
    .K_tile_in_TSTRB(K_tile_in_TSTRB),
    .K_tile_in_TLAST(K_tile_in_TLAST),
    .V_tile_in_TDATA(V_tile_in_TDATA),
    .V_tile_in_TREADY(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_in_TREADY),
    .V_tile_in_TKEEP(V_tile_in_TKEEP),
    .V_tile_in_TSTRB(V_tile_in_TSTRB),
    .V_tile_in_TLAST(V_tile_in_TLAST)
);

flashattn_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3 grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start),
    .ap_done(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_done),
    .ap_idle(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_idle),
    .ap_ready(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_ready),
    .O_tile_out_TREADY(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TREADY),
    .Q_tile_address0(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_Q_tile_address0),
    .Q_tile_ce0(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_Q_tile_ce0),
    .Q_tile_q0(Q_tile_q0),
    .K_tile_address0(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_K_tile_address0),
    .K_tile_ce0(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_K_tile_ce0),
    .K_tile_q0(K_tile_q0),
    .V_tile_address0(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_V_tile_address0),
    .V_tile_ce0(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_V_tile_ce0),
    .V_tile_q0(V_tile_q0),
    .O_tile_out_TDATA(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TDATA),
    .O_tile_out_TVALID(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID),
    .O_tile_out_TKEEP(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TKEEP),
    .O_tile_out_TSTRB(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TSTRB),
    .O_tile_out_TLAST(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TLAST)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start_reg <= 1'b1;
        end else if ((grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_ready == 1'b1)) begin
            grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start_reg <= 1'b1;
        end else if ((grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_ready == 1'b1)) begin
            grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start_reg <= 1'b1;
        end else if ((grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_ready == 1'b1)) begin
            grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID == 1'b1))) begin
        O_tile_out_TDATA_reg <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TDATA;
        O_tile_out_TKEEP_reg <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TKEEP;
        O_tile_out_TLAST_reg <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TLAST;
        O_tile_out_TSTRB_reg <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TSTRB;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        K_tile_address0 = grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_K_tile_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        K_tile_address0 = grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_address0;
    end else begin
        K_tile_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        K_tile_ce0 = grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_K_tile_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        K_tile_ce0 = grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_ce0;
    end else begin
        K_tile_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_tile_in_TREADY = grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_in_TREADY;
    end else begin
        K_tile_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_tile_we0 = grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_we0;
    end else begin
        K_tile_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID == 1'b1))) begin
        O_tile_out_TDATA = grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TDATA;
    end else begin
        O_tile_out_TDATA = O_tile_out_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID == 1'b1))) begin
        O_tile_out_TKEEP = grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TKEEP;
    end else begin
        O_tile_out_TKEEP = O_tile_out_TKEEP_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID == 1'b1))) begin
        O_tile_out_TLAST = grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TLAST;
    end else begin
        O_tile_out_TLAST = O_tile_out_TLAST_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID == 1'b1))) begin
        O_tile_out_TSTRB = grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TSTRB;
    end else begin
        O_tile_out_TSTRB = O_tile_out_TSTRB_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_tile_address0 = grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_Q_tile_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_tile_address0 = grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_address0;
    end else begin
        Q_tile_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_tile_ce0 = grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_Q_tile_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_tile_ce0 = grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_ce0;
    end else begin
        Q_tile_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_tile_in_TREADY = grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_in_TREADY;
    end else begin
        Q_tile_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_tile_we0 = grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_we0;
    end else begin
        Q_tile_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        V_tile_address0 = grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_V_tile_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        V_tile_address0 = grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_address0;
    end else begin
        V_tile_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        V_tile_ce0 = grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_V_tile_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        V_tile_ce0 = grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_ce0;
    end else begin
        V_tile_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_tile_in_TREADY = grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_in_TREADY;
    end else begin
        V_tile_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_tile_we0 = grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_we0;
    end else begin
        V_tile_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign O_tile_out_TVALID = grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_done == 1'b0) | (grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_done == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TREADY = (ap_CS_fsm_state4 & O_tile_out_TREADY);

assign grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start = grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start_reg;

assign grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start = grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start_reg;

assign grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start = grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start_reg;


reg find_kernel_block = 0;
// synthesis translate_off
`include "flashattn_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //flashattn

