-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity flashattn is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    Q_tile_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    Q_tile_in_TVALID : IN STD_LOGIC;
    Q_tile_in_TREADY : OUT STD_LOGIC;
    Q_tile_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    Q_tile_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    Q_tile_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    K_tile_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    K_tile_in_TVALID : IN STD_LOGIC;
    K_tile_in_TREADY : OUT STD_LOGIC;
    K_tile_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    K_tile_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    K_tile_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    V_tile_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    V_tile_in_TVALID : IN STD_LOGIC;
    V_tile_in_TREADY : OUT STD_LOGIC;
    V_tile_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    V_tile_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    V_tile_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    O_tile_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    O_tile_out_TVALID : OUT STD_LOGIC;
    O_tile_out_TREADY : IN STD_LOGIC;
    O_tile_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    O_tile_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    O_tile_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of flashattn is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "flashattn_flashattn,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=8212,HLS_SYN_TPT=none,HLS_SYN_MEM=24,HLS_SYN_DSP=0,HLS_SYN_FF=881,HLS_SYN_LUT=1589,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_rst_n_inv : STD_LOGIC;
    signal Q_tile_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal Q_tile_ce0 : STD_LOGIC;
    signal Q_tile_we0 : STD_LOGIC;
    signal Q_tile_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal K_tile_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal K_tile_ce0 : STD_LOGIC;
    signal K_tile_we0 : STD_LOGIC;
    signal K_tile_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal V_tile_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal V_tile_ce0 : STD_LOGIC;
    signal V_tile_we0 : STD_LOGIC;
    signal V_tile_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start : STD_LOGIC;
    signal grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_done : STD_LOGIC;
    signal grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_idle : STD_LOGIC;
    signal grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_ready : STD_LOGIC;
    signal grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_ce0 : STD_LOGIC;
    signal grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_we0 : STD_LOGIC;
    signal grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_in_TREADY : STD_LOGIC;
    signal grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start : STD_LOGIC;
    signal grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_done : STD_LOGIC;
    signal grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_idle : STD_LOGIC;
    signal grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_ready : STD_LOGIC;
    signal grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_ce0 : STD_LOGIC;
    signal grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_we0 : STD_LOGIC;
    signal grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_ce0 : STD_LOGIC;
    signal grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_we0 : STD_LOGIC;
    signal grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_in_TREADY : STD_LOGIC;
    signal grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_in_TREADY : STD_LOGIC;
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start : STD_LOGIC;
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_done : STD_LOGIC;
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_idle : STD_LOGIC;
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_ready : STD_LOGIC;
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TREADY : STD_LOGIC;
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_Q_tile_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_Q_tile_ce0 : STD_LOGIC;
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_K_tile_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_K_tile_ce0 : STD_LOGIC;
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_V_tile_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_V_tile_ce0 : STD_LOGIC;
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID : STD_LOGIC;
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start_reg : STD_LOGIC := '0';
    signal grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal O_tile_out_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal O_tile_out_TKEEP_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal O_tile_out_TSTRB_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal O_tile_out_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component flashattn_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        Q_tile_in_TVALID : IN STD_LOGIC;
        Q_tile_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        Q_tile_ce0 : OUT STD_LOGIC;
        Q_tile_we0 : OUT STD_LOGIC;
        Q_tile_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        Q_tile_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        Q_tile_in_TREADY : OUT STD_LOGIC;
        Q_tile_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        Q_tile_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        Q_tile_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component flashattn_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        K_tile_in_TVALID : IN STD_LOGIC;
        V_tile_in_TVALID : IN STD_LOGIC;
        K_tile_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        K_tile_ce0 : OUT STD_LOGIC;
        K_tile_we0 : OUT STD_LOGIC;
        K_tile_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        V_tile_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        V_tile_ce0 : OUT STD_LOGIC;
        V_tile_we0 : OUT STD_LOGIC;
        V_tile_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        K_tile_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        K_tile_in_TREADY : OUT STD_LOGIC;
        K_tile_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        K_tile_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        K_tile_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        V_tile_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        V_tile_in_TREADY : OUT STD_LOGIC;
        V_tile_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        V_tile_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        V_tile_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component flashattn_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        O_tile_out_TREADY : IN STD_LOGIC;
        Q_tile_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        Q_tile_ce0 : OUT STD_LOGIC;
        Q_tile_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        K_tile_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        K_tile_ce0 : OUT STD_LOGIC;
        K_tile_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        V_tile_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        V_tile_ce0 : OUT STD_LOGIC;
        V_tile_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        O_tile_out_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        O_tile_out_TVALID : OUT STD_LOGIC;
        O_tile_out_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        O_tile_out_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        O_tile_out_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component flashattn_Q_tile_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    Q_tile_U : component flashattn_Q_tile_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => Q_tile_address0,
        ce0 => Q_tile_ce0,
        we0 => Q_tile_we0,
        d0 => grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_d0,
        q0 => Q_tile_q0);

    K_tile_U : component flashattn_Q_tile_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => K_tile_address0,
        ce0 => K_tile_ce0,
        we0 => K_tile_we0,
        d0 => grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_d0,
        q0 => K_tile_q0);

    V_tile_U : component flashattn_Q_tile_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => V_tile_address0,
        ce0 => V_tile_ce0,
        we0 => V_tile_we0,
        d0 => grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_d0,
        q0 => V_tile_q0);

    grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82 : component flashattn_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start,
        ap_done => grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_done,
        ap_idle => grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_idle,
        ap_ready => grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_ready,
        Q_tile_in_TVALID => Q_tile_in_TVALID,
        Q_tile_address0 => grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_address0,
        Q_tile_ce0 => grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_ce0,
        Q_tile_we0 => grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_we0,
        Q_tile_d0 => grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_d0,
        Q_tile_in_TDATA => Q_tile_in_TDATA,
        Q_tile_in_TREADY => grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_in_TREADY,
        Q_tile_in_TKEEP => Q_tile_in_TKEEP,
        Q_tile_in_TSTRB => Q_tile_in_TSTRB,
        Q_tile_in_TLAST => Q_tile_in_TLAST);

    grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96 : component flashattn_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start,
        ap_done => grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_done,
        ap_idle => grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_idle,
        ap_ready => grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_ready,
        K_tile_in_TVALID => K_tile_in_TVALID,
        V_tile_in_TVALID => V_tile_in_TVALID,
        K_tile_address0 => grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_address0,
        K_tile_ce0 => grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_ce0,
        K_tile_we0 => grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_we0,
        K_tile_d0 => grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_d0,
        V_tile_address0 => grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_address0,
        V_tile_ce0 => grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_ce0,
        V_tile_we0 => grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_we0,
        V_tile_d0 => grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_d0,
        K_tile_in_TDATA => K_tile_in_TDATA,
        K_tile_in_TREADY => grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_in_TREADY,
        K_tile_in_TKEEP => K_tile_in_TKEEP,
        K_tile_in_TSTRB => K_tile_in_TSTRB,
        K_tile_in_TLAST => K_tile_in_TLAST,
        V_tile_in_TDATA => V_tile_in_TDATA,
        V_tile_in_TREADY => grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_in_TREADY,
        V_tile_in_TKEEP => V_tile_in_TKEEP,
        V_tile_in_TSTRB => V_tile_in_TSTRB,
        V_tile_in_TLAST => V_tile_in_TLAST);

    grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120 : component flashattn_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start,
        ap_done => grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_done,
        ap_idle => grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_idle,
        ap_ready => grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_ready,
        O_tile_out_TREADY => grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TREADY,
        Q_tile_address0 => grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_Q_tile_address0,
        Q_tile_ce0 => grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_Q_tile_ce0,
        Q_tile_q0 => Q_tile_q0,
        K_tile_address0 => grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_K_tile_address0,
        K_tile_ce0 => grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_K_tile_ce0,
        K_tile_q0 => K_tile_q0,
        V_tile_address0 => grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_V_tile_address0,
        V_tile_ce0 => grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_V_tile_ce0,
        V_tile_q0 => V_tile_q0,
        O_tile_out_TDATA => grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TDATA,
        O_tile_out_TVALID => grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID,
        O_tile_out_TKEEP => grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TKEEP,
        O_tile_out_TSTRB => grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TSTRB,
        O_tile_out_TLAST => grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TLAST);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_ready = ap_const_logic_1)) then 
                    grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_ready = ap_const_logic_1)) then 
                    grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
                    grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_ready = ap_const_logic_1)) then 
                    grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID = ap_const_logic_1))) then
                O_tile_out_TDATA_reg <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TDATA;
                O_tile_out_TKEEP_reg <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TKEEP;
                O_tile_out_TLAST_reg <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TLAST;
                O_tile_out_TSTRB_reg <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TSTRB;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_done, ap_CS_fsm, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_boolean_0 = ap_block_state2_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;

    K_tile_address0_assign_proc : process(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_address0, grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_K_tile_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_tile_address0 <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_K_tile_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_tile_address0 <= grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_address0;
        else 
            K_tile_address0 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    K_tile_ce0_assign_proc : process(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_ce0, grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_K_tile_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_tile_ce0 <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_K_tile_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_tile_ce0 <= grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_ce0;
        else 
            K_tile_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    K_tile_in_TREADY_assign_proc : process(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_in_TREADY, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_tile_in_TREADY <= grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_in_TREADY;
        else 
            K_tile_in_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    K_tile_we0_assign_proc : process(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_tile_we0 <= grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_K_tile_we0;
        else 
            K_tile_we0 <= ap_const_logic_0;
        end if; 
    end process;


    O_tile_out_TDATA_assign_proc : process(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TDATA, grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID, ap_CS_fsm_state4, O_tile_out_TDATA_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID = ap_const_logic_1))) then 
            O_tile_out_TDATA <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TDATA;
        else 
            O_tile_out_TDATA <= O_tile_out_TDATA_reg;
        end if; 
    end process;


    O_tile_out_TKEEP_assign_proc : process(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID, grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TKEEP, ap_CS_fsm_state4, O_tile_out_TKEEP_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID = ap_const_logic_1))) then 
            O_tile_out_TKEEP <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TKEEP;
        else 
            O_tile_out_TKEEP <= O_tile_out_TKEEP_reg;
        end if; 
    end process;


    O_tile_out_TLAST_assign_proc : process(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID, grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TLAST, ap_CS_fsm_state4, O_tile_out_TLAST_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID = ap_const_logic_1))) then 
            O_tile_out_TLAST <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TLAST;
        else 
            O_tile_out_TLAST <= O_tile_out_TLAST_reg;
        end if; 
    end process;


    O_tile_out_TSTRB_assign_proc : process(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID, grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TSTRB, ap_CS_fsm_state4, O_tile_out_TSTRB_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID = ap_const_logic_1))) then 
            O_tile_out_TSTRB <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TSTRB;
        else 
            O_tile_out_TSTRB <= O_tile_out_TSTRB_reg;
        end if; 
    end process;

    O_tile_out_TVALID <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TVALID;

    Q_tile_address0_assign_proc : process(grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_address0, grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_Q_tile_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_tile_address0 <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_Q_tile_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_tile_address0 <= grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_address0;
        else 
            Q_tile_address0 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    Q_tile_ce0_assign_proc : process(grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_ce0, grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_Q_tile_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_tile_ce0 <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_Q_tile_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_tile_ce0 <= grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_ce0;
        else 
            Q_tile_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    Q_tile_in_TREADY_assign_proc : process(grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_in_TREADY, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_tile_in_TREADY <= grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_in_TREADY;
        else 
            Q_tile_in_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    Q_tile_we0_assign_proc : process(grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_tile_we0 <= grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_Q_tile_we0;
        else 
            Q_tile_we0 <= ap_const_logic_0;
        end if; 
    end process;


    V_tile_address0_assign_proc : process(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_address0, grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_V_tile_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            V_tile_address0 <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_V_tile_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_tile_address0 <= grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_address0;
        else 
            V_tile_address0 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    V_tile_ce0_assign_proc : process(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_ce0, grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_V_tile_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            V_tile_ce0 <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_V_tile_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_tile_ce0 <= grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_ce0;
        else 
            V_tile_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    V_tile_in_TREADY_assign_proc : process(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_in_TREADY, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_tile_in_TREADY <= grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_in_TREADY;
        else 
            V_tile_in_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    V_tile_we0_assign_proc : process(grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_tile_we0 <= grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_V_tile_we0;
        else 
            V_tile_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;

    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_on_subcall_done)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_done)
    begin
        if ((grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_done, grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_done = ap_const_logic_0) or (grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_done = ap_const_logic_0));
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_O_tile_out_TREADY <= (ap_CS_fsm_state4 and O_tile_out_TREADY);
    grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start <= grp_flashattn_Pipeline_Attention_Loop_VITIS_LOOP_48_3_fu_120_ap_start_reg;
    grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start <= grp_flashattn_Pipeline_Read_K_and_V_VITIS_LOOP_35_2_fu_96_ap_start_reg;
    grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start <= grp_flashattn_Pipeline_Read_Q_VITIS_LOOP_25_1_fu_82_ap_start_reg;
end behav;
