# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/flashattn_bd/flashattn_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==flashattn_bd || ORIG_REF_NAME==flashattn_bd} -quiet] -quiet

# IP: bd/flashattn_bd/ip/flashattn_bd_processing_system7_0_0/flashattn_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==flashattn_bd_processing_system7_0_0 || ORIG_REF_NAME==flashattn_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/flashattn_bd/ip/flashattn_bd_axi_dma_0_0/flashattn_bd_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==flashattn_bd_axi_dma_0_0 || ORIG_REF_NAME==flashattn_bd_axi_dma_0_0} -quiet] -quiet

# IP: bd/flashattn_bd/ip/flashattn_bd_axi_dma_1_0/flashattn_bd_axi_dma_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==flashattn_bd_axi_dma_1_0 || ORIG_REF_NAME==flashattn_bd_axi_dma_1_0} -quiet] -quiet

# IP: bd/flashattn_bd/ip/flashattn_bd_axi_dma_2_0/flashattn_bd_axi_dma_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==flashattn_bd_axi_dma_2_0 || ORIG_REF_NAME==flashattn_bd_axi_dma_2_0} -quiet] -quiet

# IP: bd/flashattn_bd/ip/flashattn_bd_axi_dma_3_0/flashattn_bd_axi_dma_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==flashattn_bd_axi_dma_3_0 || ORIG_REF_NAME==flashattn_bd_axi_dma_3_0} -quiet] -quiet

# IP: bd/flashattn_bd/ip/flashattn_bd_axi_smc_0/flashattn_bd_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==flashattn_bd_axi_smc_0 || ORIG_REF_NAME==flashattn_bd_axi_smc_0} -quiet] -quiet

# IP: bd/flashattn_bd/ip/flashattn_bd_rst_ps7_0_100M_0/flashattn_bd_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==flashattn_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==flashattn_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_xbar_0/flashattn_bd_axi_interconnect_0_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==flashattn_bd_axi_interconnect_0_imp_xbar_0 || ORIG_REF_NAME==flashattn_bd_axi_interconnect_0_imp_xbar_0} -quiet] -quiet

# IP: bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_0/flashattn_bd_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==flashattn_bd_axi_interconnect_0_0 || ORIG_REF_NAME==flashattn_bd_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/flashattn_bd/ip/flashattn_bd_flashattn_0_1/flashattn_bd_flashattn_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==flashattn_bd_flashattn_0_1 || ORIG_REF_NAME==flashattn_bd_flashattn_0_1} -quiet] -quiet

# IP: bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_auto_us_0/flashattn_bd_axi_interconnect_0_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==flashattn_bd_axi_interconnect_0_imp_auto_us_0 || ORIG_REF_NAME==flashattn_bd_axi_interconnect_0_imp_auto_us_0} -quiet] -quiet

# IP: bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_auto_us_1/flashattn_bd_axi_interconnect_0_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==flashattn_bd_axi_interconnect_0_imp_auto_us_1 || ORIG_REF_NAME==flashattn_bd_axi_interconnect_0_imp_auto_us_1} -quiet] -quiet

# IP: bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_auto_us_2/flashattn_bd_axi_interconnect_0_imp_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==flashattn_bd_axi_interconnect_0_imp_auto_us_2 || ORIG_REF_NAME==flashattn_bd_axi_interconnect_0_imp_auto_us_2} -quiet] -quiet

# IP: bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_auto_us_3/flashattn_bd_axi_interconnect_0_imp_auto_us_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==flashattn_bd_axi_interconnect_0_imp_auto_us_3 || ORIG_REF_NAME==flashattn_bd_axi_interconnect_0_imp_auto_us_3} -quiet] -quiet

# IP: bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_auto_pc_0/flashattn_bd_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==flashattn_bd_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==flashattn_bd_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/cfk30/OneDrive/Documents/ECE4910/thesis/flash_attn_vivado/flash_attn_vivado.gen/sources_1/bd/flashattn_bd/flashattn_bd_ooc.xdc
