# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/cfk30/OneDrive/Documents/ECE4910/thesis/flash_attn_vivado/flash_attn_vivado.srcs/sources_1/bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_auto_us_1/flashattn_bd_axi_interconnect_0_imp_auto_us_1.xci
# IP: The module: 'flashattn_bd_axi_interconnect_0_imp_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cfk30/OneDrive/Documents/ECE4910/thesis/flash_attn_vivado/flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_auto_us_1/flashattn_bd_axi_interconnect_0_imp_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'flashattn_bd_axi_interconnect_0_imp_auto_us_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/cfk30/OneDrive/Documents/ECE4910/thesis/flash_attn_vivado/flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_auto_us_1/flashattn_bd_axi_interconnect_0_imp_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'flashattn_bd_axi_interconnect_0_imp_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/cfk30/OneDrive/Documents/ECE4910/thesis/flash_attn_vivado/flash_attn_vivado.srcs/sources_1/bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_auto_us_1/flashattn_bd_axi_interconnect_0_imp_auto_us_1.xci
# IP: The module: 'flashattn_bd_axi_interconnect_0_imp_auto_us_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cfk30/OneDrive/Documents/ECE4910/thesis/flash_attn_vivado/flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_auto_us_1/flashattn_bd_axi_interconnect_0_imp_auto_us_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'flashattn_bd_axi_interconnect_0_imp_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/cfk30/OneDrive/Documents/ECE4910/thesis/flash_attn_vivado/flash_attn_vivado.gen/sources_1/bd/flashattn_bd/ip/flashattn_bd_axi_interconnect_0_imp_auto_us_1/flashattn_bd_axi_interconnect_0_imp_auto_us_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'flashattn_bd_axi_interconnect_0_imp_auto_us_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
